import 'package:flippy_pairs/PROCEDIMIENTOS/SERVICIOS/srv_diskette.dart';

class SrvTraducciones {
  static final Map<String, String> english = {
    'subtitulo_app': 'Harden Your Mind Once and for All!',
    'configuracion': 'Settings...',
    'comenzar_juego': 'Start Playing!',
    'temas': 'Themes',
    'dificultad': 'Difficulty',
    'texto_alias': 'Please enter the alias you wish to use in the FWC (Flippy World Competition)...',
    'alias': 'Alias',
    'alias_hint': 'Enter a name you like...',
    'activar_sonidos': 'Turn Sounds On or Off...',
    'activar_musica': 'Turn Music On or Off...',
    'grabar_datos': 'Save Data',
    'datos_guardados': 'Data saved successfully',
    'puntos': 'Points',
    'aciertos': 'Match',
    'errores': 'Fail',
    'timer': 'Timer',
    'ganada1': '🎉 Excellent!',
    'ganada2': '🌟 Wunderbar!',
    'ganada3': '👽 Outta Sight!',
    'ganada4': '💥 Smashing!',
    'ganada5': '👑 Fantabulistic',
    'perdida1': '😅 Oooppss!',
    'perdida2': '😵‍💫 Not This Time!',
    'perdida3': '👻 You Got Ghosted',
    'perdida4': '💧 Melted',
    'perdida5': '🤡 Bummer!',
    'empatada1': '🎯 You nailed it!',
    'empatada2': '⚖️ Perfectly Balanced',
    'empatada3': '✨ Perfectly Neutral',
    'empatada4': '🏆 Champion of Zero',
    'empatada5': '🌌 A Perfect Non-Score',
    'has_ganado': "You've won ### points in this game. Congratulations!",
    'has_perdido': "You've lost ### points in this game. You can do it better...",
    'has_empatado': "No points gained… no points lost. Just in the middle! Give it another go!",
    'puntuacion_total': 'Your total score:',
    'finalizado_en': 'Game finished in:',
    'volver_a_jugar': 'Play again',
    'salir': 'Exit',
    'fin_del_juego': 'End of Game',
    'tiempo_medio': 'Average time of others:',
    'partidas_jugadas': 'Matches played:',
    'tiempo_record': 'Your best time is:',
    'selec_idioma': 'Select a language...',
    'pos_flippy': 'Your ranking in the FWC:',
    'nivel': 'Level',
    'lento': '🐌 Slow',
    'normal': '🏃 Normal',
    'rapido': '🚀 Fast',
    'velocidad_juego': 'Game Speed',
    'ranking': 'Ranking',
    'primeros': 'The Protagonists',
    'segundos': 'The Guest Stars',
    'terceros': 'The Extras',
    'cuartos': 'The Bad Guys',
    'primerost': 'The Astronauts',
    'segundost': 'The Speed Demons',
    'tercerost': 'The Bike Riders',
    'cuartost': 'The Scooter Gang',
    'primerosp': 'Point Pantheon',
    'segundosp': 'The Comfort Zone',
    'tercerosp': 'Finding North',
    'todos': 'All Players',
    'estas_en_posicion': 'You are in position ',
    'sin_datos': 'No available data',
    'no_has_jugado': "You still haven't played in this Level",
    'eliminar_mis_puntuaciones': 'Delete my scores',
    'borrar_puntuacion': 'Delete Scores',
    'seguro_eliminar_puntos': 'Are you sure you want to delete all your rankings? This action cannot be undone.',
    'borrar': 'Delete',
    'cancelar': 'Cancel',
    'puntuaciones_eliminadas': '🗑️ Scores deleted!',
  };

  static final Map<String, String> spanish = {
    'subtitulo_app': 'Endurece tu mente de una vez por todas!',
    'configuracion': 'Configuración...',
    'comenzar_juego': 'Jugar!',
    'temas': 'Temas',
    'dificultad': 'Dificultad',
    'texto_alias':
        'Por favor, introduce el alias con el que quieres aparecer en la CMF (Competición Mundial Flippy)...',
    'alias': 'Alias',
    'alias_hint': 'Introduce un nombre que te guste...',
    'activar_sonidos': 'Activar o desactivar sonidos...',
    'activar_musica': 'Activar o desactivar música...',
    'grabar_datos': 'Guardar datos',
    'datos_guardados': 'Datos guardados correctamente',
    'puntos': 'Puntos',
    'aciertos': 'OK',
    'errores': 'KO',
    'timer': 'Timer',
    'ganada1': '🎉 ¡Excelente!',
    'ganada2': '🌟 Wunderbar!',
    'ganada3': '👽 ¡De locura!',
    'ganada4': '💥 ¡Aplausos!',
    'ganada5': '👑 ¡Fabuloso!',
    'perdida1': '😅 ¡Oooppss!',
    'perdida2': '😵‍💫 ¡A la Próxima!',
    'perdida3': '👻 ¡Hasta Luego!',
    'perdida4': '💧 Derretido',
    'perdida5': '🤡 ¡Qué Faena!',
    'empatada1': '🎯 ¡La clavaste!',
    'empatada2': '⚖️ Balance perfecto',
    'empatada3': '✨ Neutro total',
    'empatada4': '🏆 Campeón del Cero',
    'empatada5': '🌌 Vacio absoluto',
    'has_ganado': "Has ganado ### puntos en esta partida. Felicidades!",
    'has_perdido': "Has perdido ### puntos en esta partida. Puedes hacerlo mejor...",
    'has_empatado': "Ni puntos ganados ni perdidos. Justo en el medio! Vuelve a intentarlo!",
    'puntuacion_total': 'Puntuación total:',
    'finalizado_en': 'Partida finalizada en:',
    'volver_a_jugar': 'Volver a jugar',
    'salir': 'Salir',
    'fin_del_juego': 'Fin del juego',
    'tiempo_medio': 'Tiempo medio de otros:',
    'partidas_jugadas': 'Partidas jugadas:',
    'tiempo_record': 'Tu tiempo record es:',
    'selec_idioma': "Selecciona un idioma...",
    'pos_flippy': 'Tu ranking en la CMF:',
    'nivel': 'Nivel',
    'lento': '🐌 Lento',
    'normal': '🏃 Normal',
    'rapido': '🚀 Rápido',
    'velocidad_juego': 'Velocidad',
    'ranking': 'Ranking',
    'primeros': 'Los Protagonistas',
    'segundos': 'Los Invitados',
    'terceros': 'Los Extras',
    'cuartos': 'Los Chicos Malos',
    'primerost': 'Los Astronautas',
    'segundost': 'Los Pilotos',
    'tercerost': 'Los Ciclistas',
    'cuartost': 'Los del Patín',
    'primerosp': 'Panteón de Puntos',
    'segundosp': 'La Zona de Confort',
    'tercerosp': 'Buscando el Norte',
    'todos': 'Todos los Jugadores',
    'estas_en_posicion': 'Estás en la posición ',
    'sin_datos': 'No hay datos disponibles',
    'no_has_jugado': "Todavía no has jugado en este Nivel",
    'eliminar_mis_puntuaciones': 'Eliminar mis puntuaciones',
    'borrar_puntuacion': 'Eliminar Puntuación',
    'seguro_eliminar_puntos':
        '¿Estás seguro de que quieres eliminar todas tus puntuaciones? Esta acción no se puede deshacer.',
    'borrar': 'Borrar',
    'cancelar': 'Cancelar',
    'puntuaciones_eliminadas': '🗑️ Puntuaciones eliminadas!',
  };

  static final Map<String, String> catalan = {
    'subtitulo_app': "Endureix la teva ment d'una vegada per totes!",
    'configuracion': 'Configuració...',
    'comenzar_juego': 'Juga!',
    'temas': 'Temes',
    'dificultad': 'Dificultat',
    'texto_alias': "Si us plau, introdueix l'àlies amb el qual vols aparèixer a la CMF (Competició Mundial Flippy)...",
    'alias': 'Àlies',
    'alias_hint': "Introdueix un nom que t'agradi...",
    'activar_sonidos': 'Activar o desactivar sons...',
    'activar_musica': 'Activar o desactivar música...',
    'grabar_datos': 'Desar dades',
    'datos_guardados': 'Dades desades correctament',
    'puntos': 'Punts',
    'aciertos': 'OK',
    'errores': 'KO',
    'timer': 'Timer',
    'ganada1': '🎉 Excel·lent!',
    'ganada2': '🌟 Wunderbar!',
    'ganada3': '👽 De bogeria!',
    'ganada4': '💥 Molt Bé!',
    'ganada5': '👑 Fabulós!',
    'perdida1': '😅 Uix, S\'ha Escapat!',
    'perdida2': '😵‍💫 La Pròxima!',
    'perdida3': '👻 Fins Després!',
    'perdida4': '💧 Desfet',
    'perdida5': '🤡 Quina Pena!',
    'empatada1': '🎯 L\'has Clavat!',
    'empatada2': '⚖️ Balanç Perfecte',
    'empatada3': '✨ Neutre total',
    'empatada4': '🏆 Campió del Zero',
    'empatada5': '🌌 Buit Absolut',
    'has_ganado': "Has guanyat ### punts en aquesta partida. Felicitats!",
    'has_perdido': "Has perdut ### punts en aquesta partida. Pots fer-ho millor...",
    'has_empatado': "Ni punts guanyats ni perduts. Just al mig! Torna a jugar!",
    'puntuacion_total': 'Puntuació total:',
    'finalizado_en': 'Partida finalitzada en:',
    'volver_a_jugar': 'Torna a jugar',
    'salir': 'Surt',
    'fin_del_juego': 'Fi del joc',
    'tiempo_medio': 'Temps mitjà dels altres:',
    'partidas_jugadas': 'Partides jugades:',
    'tiempo_record': 'El teu temps rècord és:',
    'selec_idioma': "Tria un idioma...",
    'pos_flippy': 'El teu ranking a la CMF',
    'nivel': 'Nivell',
    'lento': '🐌 Lent',
    'normal': '🏃 Normal',
    'rapido': '🚀 Ràpid',
    'velocidad_juego': 'Velocitat',
    'ranking': 'Ranking',
    'primeros': 'Els Protagonistes',
    'segundos': 'Els Convidats',
    'terceros': 'Els Extres',
    'cuartos': 'Els Nois Dolents',
    'primerost': 'Els Astronautes',
    'segundost': 'Els Pilots',
    'tercerost': 'Els Ciclistes',
    'cuartost': 'Els del Patinet',
    'primerosp': 'Panteó de Punts',
    'segundosp': 'La Zona de Confort',
    'tercerosp': 'Buscant el Nort',
    'todos': 'Tots els Jugadors',
    'estas_en_posicion': 'Estàs a la posició ',
    'sin_datos': "No n'hi han dades disponibles",
    'no_has_jugado': "Encara no has jugat en aquest Nivell",
    'eliminar_mis_puntuaciones': 'Eliminar les meves puntuacions',
    'borrar_puntuacion': 'Eliminar Puntuació',
    'seguro_eliminar_puntos':
        'Estàs segur de que vols eliminar totes les teves puntuacións? Aquesta acció no es pot desfer.',
    'borrar': 'Esborrar',
    'cancelar': 'Cancel·lar',
    'puntuaciones_eliminadas': '🗑️ Puntuacions esborrades!',
  };

  //----------------------------------------------------------------------------
  // Obtenemos una traducción.
  //----------------------------------------------------------------------------

  static String get(String pId, {String pArgumento = ''}) {
    String output = '';
    String idioma = SrvDiskette.leerValor(DisketteKey.idioma, defaultValue: 'en');
    switch (idioma) {
      case 'es':
        output = spanish[pId] == null ? pId : spanish[pId]!;
        break;
      case 'ca':
        output = catalan[pId] == null ? pId : catalan[pId]!;
        break;

      default:
        output = english[pId] == null ? pId : english[pId]!;
    }
    if (pArgumento != '') {
      output = output.replaceAll('###', pArgumento);
    }
    return output;
  }
}
